# installs the `.container` file on the current host
container-install: dockerfile-build podman-save && systemd-reload systemd-start-service
  sudo mkdir -p /etc/containers/systemd/mailqueue
  sudo cp mailqueue.container mailqueue-image.tar mailqueue.env /etc/containers/systemd/mailqueue/

container-uninstall: && systemd-stop-service systemd-reload
  sudo rm -rf /etc/containers/systemd/mailqueue

systemd-reload:
  sudo systemctl daemon-reload

systemd-start-service:
  sudo systemctl start mailqueue.service

systemd-stop-service:
  sudo systemctl stop mailqueue.service

dockerfile-build:
    podman build .. --no-cache --rm --tag mailqueue -f ./mailqueue.Dockerfile

# saves the docker image into a `.tar` file
podman-save:
    rm -f ./mailqueue-image.tar
    podman save --output ./mailqueue-image.tar localhost/mailqueue

release-make-zip:
  zip -r mailqueue.release.zip mailqueue.container mailqueue.env mailqueue-image.tar
