set shell := ["nu", "-c"]

list:
  just --list

# requires podman and `cargo install cross-rs`
build-cross-rpi:
  cross build --target=aarch64-unknown-linux-gnu

build-cross-rpi-release:
  cross build --release --target=aarch64-unknown-linux-gnu

deploy-build-cross-rpi:
  scp ../../target/aarch64-unknown-linux-gnu/debug/cai-reverse-proxy-example rpi:~/cai-reverse-proxy-example
  ssh rpi "sudo chmod +x ~/cai-reverse-proxy-example"

deploy-build-cross-rpi-release:
  scp ../../target/aarch64-unknown-linux-gnu/release/cai-reverse-proxy-example rpi:~/cai-reverse-proxy-example
  ssh rpi "sudo chmod +x ~/cai-reverse-proxy-example"

podman-start:
  podman machine start