set shell := ["nu", "-c"]

list:
  just --list

# requires podman and `cargo install cross-rs`
build-cross-rpi:
  cross build --target=aarch64-unknown-linux-gnu

build-cross-rpi-release:
  cross build --release --target=aarch64-unknown-linux-gnu

deploy-build-cross-rpi:
  scp ../../target/aarch64-unknown-linux-gnu/debug/cai-reverse-proxy-example rpi:~/cai-reverse-proxy-example
  ssh rpi "sudo chmod +x ~/cai-reverse-proxy-example"

deploy-build-cross-rpi-release:
  scp ../../target/aarch64-unknown-linux-gnu/release/cai-reverse-proxy-example rpi:~/cai-reverse-proxy-example
  ssh rpi "sudo chmod +x ~/cai-reverse-proxy-example"

podman-start:
  podman machine start

dockerfile-build:
  podman build ../../ --rm --tag cai-reverse-proxy -f cai-reverse-proxy.Dockerfile

compose-start:
  podman compose -p cai-reverse-proxy -f docker/cai-reverse-proxy/docker-compose.yml start

compose-up:
  podman compose -p cai-reverse-proxy -f docker/cai-reverse-proxy/docker-compose.yml up

compose-stop:
  podman compose -p cai-reverse-proxy -f docker/cai-reverse-proxy/docker-compose.yml stop

compose-ls:
  podman compose -p cai-reverse-proxy -f docker/cai-reverse-proxy/docker-compose.yml ls
